---
sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  - docker pull mongo:3.4
install:
  - npm install
before_script:
  - docker run --name mongodb -d -p 27017:27017 mongo:3.4
  - docker build --tag bouncer .
  - docker run --name testbouncer -d -p 8083:8083 --link mongodb:mongodb -e OAUTH_STARTUP_TEST=false -e BOUNCER_MONGODB=mongodb://mongodb:27017 -e DEBUG=* bouncer
  - sleep 5
script:
  - DEBUG=* npm test
after_failure:
  - sleep 5
  - docker logs testbouncer
